export const HttpStatus = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export type HttpStatusCode = (typeof HttpStatus)[keyof typeof HttpStatus];

export const ErrorCode = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export enum LombokRegion {
  LOMBOK_SELATAN = 'LOMBOK_SELATAN',
  LOMBOK_UTARA = 'LOMBOK_UTARA',
  LOMBOK_BARAT = 'LOMBOK_BARAT',
  LOMBOK_TIMUR = 'LOMBOK_TIMUR',
  LOMBOK_TENGAH = 'LOMBOK_TENGAH',
  GILI_ISLANDS = 'GILI_ISLANDS',
}

export enum DifficultyLevel {
  EASY = 'EASY',
  MODERATE = 'MODERATE',
  CHALLENGING = 'CHALLENGING',
  EXTREME = 'EXTREME',
}

export enum TravelStyle {
  NATURE_ADVENTURE = 'NATURE_ADVENTURE',
  BEACH_RELAXATION = 'BEACH_RELAXATION',
  CULTURE_HERITAGE = 'CULTURE_HERITAGE',
  CULINARY_EXPLORER = 'CULINARY_EXPLORER',
  PHOTOGRAPHY_SPOTS = 'PHOTOGRAPHY_SPOTS',
  FAMILY_FRIENDLY = 'FAMILY_FRIENDLY',
}

export enum BudgetLevel {
  BUDGET = 'BUDGET',
  MID_RANGE = 'MID_RANGE',
  LUXURY = 'LUXURY',
}

export enum ExpenseCategory {
  TRANSPORT = 'TRANSPORT',
  ACCOMMODATION = 'ACCOMMODATION',
  FOOD = 'FOOD',
  ACTIVITY = 'ACTIVITY',
  SHOPPING = 'SHOPPING',
  LODGING = 'LODGING',
  TICKET = 'TICKET',
  SOUVENIR = 'SOUVENIR',
  OTHER = 'OTHER',
}

export enum ChecklistCategory {
  BEACH = 'BEACH',
  TREKKING = 'TREKKING',
  GENERAL = 'GENERAL',
  CLOTHING = 'CLOTHING',
  DOCUMENTS = 'DOCUMENTS',
}
